// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxVhQpE4b0CLz30lfHtlgRzL9NAmfGwoQ',
    appId: '1:1075893643401:web:1beac54e4de92a104afe58',
    messagingSenderId: '1075893643401',
    projectId: 'flutterchatapp-e1c1b',
    authDomain: 'flutterchatapp-e1c1b.firebaseapp.com',
    storageBucket: 'flutterchatapp-e1c1b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3jC2BknRpNtsSRJ3O-BXE5Opb6A3kGI8',
    appId: '1:1075893643401:android:6f08b51f1080839a4afe58',
    messagingSenderId: '1075893643401',
    projectId: 'flutterchatapp-e1c1b',
    storageBucket: 'flutterchatapp-e1c1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDqZBnYBm5mxSdpz8sB-VqLmEAZ_4bRDQ',
    appId: '1:1075893643401:ios:c3a54fe866207b764afe58',
    messagingSenderId: '1075893643401',
    projectId: 'flutterchatapp-e1c1b',
    storageBucket: 'flutterchatapp-e1c1b.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDqZBnYBm5mxSdpz8sB-VqLmEAZ_4bRDQ',
    appId: '1:1075893643401:ios:60dda3a0df1e96274afe58',
    messagingSenderId: '1075893643401',
    projectId: 'flutterchatapp-e1c1b',
    storageBucket: 'flutterchatapp-e1c1b.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAuth.RunnerTests',
  );
}
